spring:
  application:
    name: reflect
  datasource:
    url: jdbc:postgresql://localhost:5432/reflectdb
    username: reflect_user
    password: secretPass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs